version: "3"
services:
  # POSTGRES SQL
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  # PG ADMIN
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  # RABBIT MQ --------------------
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq_dev
    ports:
      - 5672:5672
      - 15672:15672
  # SONARQUBE
  sonarqube:
    image: sonarqube:8.9.9-community
    container_name: sonarqube
    ports:
      - 9000:9000
  # API CERSEU FISI --------------
  #  api:
  #    build: .
  #    container_name: api
  #    ports:
  #      - 8080:8080
  #    links:
  #      - rabbitmq
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
