server:
    port: 8080
# H2 o PostgreSQL --------------------------------------------
spring:
    application:
        name: api-cerseu-fisi
    datasource:
        url: jdbc:postgresql://localhost:5432/cerseu
        #url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
        #driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
            #ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                #dialect: org.hibernate.dialect.H2Dialect
    # Envio de email -----------------------------------------
    mail:
        host: smtp.gmail.com
        port: 587
        username: comidev.mail@gmail.com
        password: luxwltyrclqbnpcv
        properties:
            mail:
                smtp:
                    ssl:
                        trust: "*"
                    auth: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000
                    starttls:
                        enable: true
    # RabbitMQ (Docker) ------------------------------
    rabbitmq:
        host: localhost # docker ? rabbitmq : localhost
        port: 5672
        username: guest
        password: guest
comidev:
    # RabbitMQ (ENV) ------------------------------
    queue:
        email: send-email
    routing:
        email: routing-email
